import { BaseDirectory, exists, readTextFile } from "@tauri-apps/plugin-fs";
import { getDb } from "./core";
import { getSetting, setSetting } from "./settings";
import { createRunOnce } from "../lib/singleFlight";
import { Playlist } from "../types";

const PLAYLISTS_FILE = "playlists.json";

// One-time import of the pre-SQLite `playlists.json` (a Mac-only artifact of
// an older build). Single-flighted like initDb(): React StrictMode
// double-invokes the mount effect in dev, and without a guard both runs can
// both see an empty DB and double-INSERT the same playlists.
const migrateOnce = createRunOnce(() => migrateFromJsonOnce());

/** Test-only: drop the cached migration promise. */
export function _resetLegacyImportForTests() {
    migrateOnce.reset();
}

export async function migrateFromJson(): Promise<void> {
    return migrateOnce.run();
}

async function migrateFromJsonOnce() {
    try {
        // Durable marker set once migration succeeds — the count(*) check below
        // is kept as a second net for older installs, but on its own it conflates
        // "already migrated" with "has any playlist at all" (a folder scan, XML
        // import, or sync mirror before this ran would disable the migration
        // for good).
        if ((await getSetting("json_migrated")) === "1") return;

        const fileExists = await exists(PLAYLISTS_FILE, { baseDir: BaseDirectory.AppLocalData });
        if (!fileExists) return;

        const content = await readTextFile(PLAYLISTS_FILE, { baseDir: BaseDirectory.AppLocalData });
        const playlists: Playlist[] = JSON.parse(content);
        const db = await getDb();

        // Check if migration already happened (simple check: if playlists exist)
        const existingPlaylists: any[] = await db.select("SELECT count(*) as count FROM playlists");
        if (existingPlaylists[0].count > 0) {
            console.log("Migration skipped: DB already has data");
            await setSetting("json_migrated", "1");
            return;
        }

        console.log("Starting migration from JSON...");

        for (const playlist of playlists) {
            await db.execute(
                "INSERT INTO playlists (id, name, type) VALUES ($1, $2, $3) ON CONFLICT(id) DO NOTHING",
                [playlist.id, playlist.name, playlist.type]
            );

            for (let i = 0; i < playlist.tracks.length; i++) {
                const track = playlist.tracks[i];

                // Insert track if not exists (ignore on conflict)
                await db.execute(`
          INSERT INTO tracks (id, title, artist, album, file_path, file_name, duration)
          VALUES ($1, $2, $3, $4, $5, $6, $7)
          ON CONFLICT(file_path) DO NOTHING
        `, [
                    track.id,
                    track.title,
                    track.artist || null,
                    track.album || null,
                    track.file_path,
                    track.file_name,
                    track.duration || null
                ]);

                // Link to playlist
                // Note: The track ID in JSON might not match the one generated by scan if hashing changed.
                // But assuming JSON is source of truth for now.
                // Ideally we should select the track ID by file_path from DB to be safe if we want to enforce consistency,
                // but for migration let's assume IDs match or use ON CONFLICT DO NOTHING for links.

                // Fetch the actual track ID from DB based on file_path to ensure referential integrity
                const dbTrack: any[] = await db.select("SELECT id FROM tracks WHERE file_path = $1", [track.file_path]);
                if (dbTrack.length > 0) {
                    const trackId = dbTrack[0].id;
                    await db.execute(`
                INSERT INTO playlist_tracks (playlist_id, track_id, position)
                VALUES ($1, $2, $3)
             `, [playlist.id, trackId, i]);
                }
            }
        }
        await setSetting("json_migrated", "1");
        console.log("Migration completed.");
    } catch (err) {
        console.error("Migration failed:", err);
    }
}
