package com.voynix.ui.settings

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class LicensesScreenTest {
    @Test
    fun `licenseParagraphs splits on blank lines and drops empties`() {
        assertEquals(listOf("a\nb", "c"), licenseParagraphs("a\nb\n\n\n\nc\n\n"))
        assertEquals(listOf("a", "b"), licenseParagraphs("a\r\n\r\nb"))
    }

    @Test
    fun `bundled licenses asset covers the main libraries`() {
        // Generated by scripts/generate-licenses.mjs — regenerate after changing dependencies.
        val text = File("src/main/assets/licenses.txt").readText()
        for (needle in listOf("MIT License", "com.squareup.okhttp3:okhttp ", "androidx.room:room-runtime ", "play-services-code-scanner", "Apache License")) {
            assertTrue("licenses.txt should mention: $needle", text.contains(needle))
        }
    }
}
