package com.voynix.ui.settings

import android.content.Context
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.voynix.R
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/** assets/licenses.txt is generated by scripts/generate-licenses.mjs (`npm run licenses:generate`). */
private const val LICENSES_ASSET = "licenses.txt"

/** Splits the notices file into paragraphs so the LazyColumn only lays out what's on screen. */
internal fun licenseParagraphs(text: String): List<String> =
    text.replace("\r\n", "\n").split(Regex("\n{2,}")).filter { it.isNotBlank() }

private suspend fun loadLicenses(context: Context): List<String>? = withContext(Dispatchers.IO) {
    runCatching {
        licenseParagraphs(context.assets.open(LICENSES_ASSET).bufferedReader().use { it.readText() })
    }.getOrNull()
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LicensesScreen(context: Context, onBack: () -> Unit) {
    var paragraphs by remember { mutableStateOf<List<String>?>(null) }
    var failed by remember { mutableStateOf(false) }

    LaunchedEffect(Unit) {
        val loaded = loadLicenses(context)
        paragraphs = loaded
        failed = loaded == null
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.licenses_title)) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = stringResource(R.string.settings_back))
                    }
                },
            )
        },
    ) { padding ->
        Column(modifier = Modifier.padding(padding).fillMaxSize()) {
            val list = paragraphs
            when {
                failed -> Text(
                    stringResource(R.string.licenses_load_failed),
                    modifier = Modifier.padding(16.dp),
                    color = MaterialTheme.colorScheme.error,
                )
                list != null -> SelectionContainer {
                    LazyColumn(contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp)) {
                        items(list) { paragraph ->
                            Text(
                                paragraph,
                                modifier = Modifier.padding(vertical = 4.dp),
                                style = MaterialTheme.typography.bodySmall,
                                fontFamily = FontFamily.Monospace,
                                fontSize = 11.sp,
                            )
                        }
                    }
                }
            }
        }
    }
}
