import { describe, expect, it } from "vitest";
import pkg from "../package.json";
import cargoToml from "../src-tauri/Cargo.toml?raw";
import licenses from "../public/licenses.txt?raw";

// public/licenses.txt is generated by scripts/generate-licenses.mjs. These
// checks fail when a direct dependency was added without regenerating it
// (`npm run licenses:generate`).
const listed = (name: string) => licenses.includes(`- ${name} `);

describe("public/licenses.txt", () => {
    it("lists every npm dependency", () => {
        const missing = Object.keys(pkg.dependencies).filter(name => !listed(name));
        expect(missing).toEqual([]);
    });

    it("lists every Rust dependency of src-tauri", () => {
        const section = cargoToml.split(/^\[dependencies\]\s*$/m)[1]?.split(/^\[/m)[0] ?? "";
        const names = [...section.matchAll(/^([A-Za-z0-9_-]+)\s*=/gm)].map(m => m[1]);
        expect(names.length).toBeGreaterThan(10);
        expect(names.filter(name => !listed(name))).toEqual([]);
    });

    it("includes Voynix's own license and the bundled font", () => {
        expect(licenses).toContain("MIT License");
        expect(licenses).toContain("SIL OPEN FONT LICENSE Version 1.1");
    });
});
